Updated hefur 1.0-36

diff --git a/extra/hefur/PKGBUILD b/extra/hefur/PKGBUILD
--- a/extra/hefur/PKGBUILD
+++ b/extra/hefur/PKGBUILD
@@ -4,7 +4,8 @@
 
 pkgname=hefur
 pkgver=1.0
-pkgrel=35
+pkgrel=36
+_protobuf_ver=34.1
 pkgdesc='A standalone and lightweight BitTorrent tracker'
 arch=('x86_64')
 url='https://github.com/abique/hefur'
@@ -24,6 +25,7 @@ makedepends=(
     'cmake')
 source=("git+https://github.com/abique/hefur.git#tag=${pkgver}"
         'git+https://github.com/abique/mimosa.git'
+        "https://github.com/protocolbuffers/protobuf/archive/v${_protobuf_ver}/protobuf-${_protobuf_ver}.tar.gz"
         'hefurd.service'
         'sysusers.conf'
         'tmpfiles.conf'
@@ -31,6 +33,7 @@ source=("git+https://github.com/abique/hefur.git#tag=${pkgver}"
         '020-hefur-fix-invalid-port-set-for-https.patch'::'https://github.com/abique/hefur/commit/f8b0fe6295257a6bfd7da00b1bd9cd4da966ddeb.patch')
 sha256sums=('d6db02ee070102c6da4374edaf50f558e47559268eb4c1491bdc44a7bb4c8e04'
             'SKIP'
+            'a83103b7ed3afaeedee9a212c8f65825444f58144f5e075b73c83f2b4ff27b62'
             '3d8b0a716f35798f6aa25d6ee6a032d8a142811b920338bcb398c24beb1c8b43'
             '2e87fa1d1662d13103e4b84bc52c4f97507b06cd9982e0e9d1fec24ac495327a'
             '7d39eec7c9f004a8651de95d11d32422f0a506f0fe21d5fdf37a407a05d4de0f'
@@ -51,6 +54,19 @@ prepare() {
 }
 
 build() {
+	# workaround for protobuf 34.0+ until upstream can find a solution
+	# https://github.com/abique/hefur/issues/53
+	export CXXFLAGS+=" -isystem${srcdir}/protobuf-${_protobuf_ver}/src"
+	
+	local _system_protobuf_ver
+	_system_protobuf_ver="$(LC_ALL='C' pacman -Qi 'protobuf' | awk '/^Version/ { print $3 }' | grep -oE '^[0-9]+\.[0-9]+')"
+	
+	if [ "$_system_protobuf_ver" != "$_protobuf_ver" ]
+	then
+		printf '%s\n' 'error: protobuf version in PKGBUILD must match the repository one'
+		exit 1
+	fi
+	
 	cmake -B build -S hefur \
 		-G 'Unix Makefiles' \
 		-DCMAKE_BUILD_TYPE:STRING='None' \
